package com.hwilliams.agroServer.db.client;

import com.hwilliams.agroServer.db.model.Cotizacion;
import com.hwilliams.agroServer.db.model.CotizacionExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CotizacionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    @SelectProvider(type=CotizacionSqlProvider.class, method="countByExample")
    int countByExample(CotizacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    @DeleteProvider(type=CotizacionSqlProvider.class, method="deleteByExample")
    int deleteByExample(CotizacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    @Delete({
        "delete from cotizacion",
        "where nombre = #{nombre,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String nombre);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    @Insert({
        "insert into cotizacion (nombre, mercado, ",
        "valor, variacion)",
        "values (#{nombre,jdbcType=VARCHAR}, #{mercado,jdbcType=VARCHAR}, ",
        "#{valor,jdbcType=VARCHAR}, #{variacion,jdbcType=VARCHAR})"
    })
    int insert(Cotizacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    @InsertProvider(type=CotizacionSqlProvider.class, method="insertSelective")
    int insertSelective(Cotizacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    @SelectProvider(type=CotizacionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="nombre", property="nombre", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="mercado", property="mercado", jdbcType=JdbcType.VARCHAR),
        @Result(column="valor", property="valor", jdbcType=JdbcType.VARCHAR),
        @Result(column="variacion", property="variacion", jdbcType=JdbcType.VARCHAR)
    })
    List<Cotizacion> selectByExample(CotizacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    @Select({
        "select",
        "nombre, mercado, valor, variacion",
        "from cotizacion",
        "where nombre = #{nombre,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="nombre", property="nombre", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="mercado", property="mercado", jdbcType=JdbcType.VARCHAR),
        @Result(column="valor", property="valor", jdbcType=JdbcType.VARCHAR),
        @Result(column="variacion", property="variacion", jdbcType=JdbcType.VARCHAR)
    })
    Cotizacion selectByPrimaryKey(String nombre);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    @UpdateProvider(type=CotizacionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Cotizacion record, @Param("example") CotizacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    @UpdateProvider(type=CotizacionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Cotizacion record, @Param("example") CotizacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    @UpdateProvider(type=CotizacionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Cotizacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    @Update({
        "update cotizacion",
        "set mercado = #{mercado,jdbcType=VARCHAR},",
          "valor = #{valor,jdbcType=VARCHAR},",
          "variacion = #{variacion,jdbcType=VARCHAR}",
        "where nombre = #{nombre,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Cotizacion record);
}