package com.hwilliams.agroServer.db.client;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hwilliams.agroServer.db.model.Cotizacion;
import com.hwilliams.agroServer.db.model.CotizacionExample.Criteria;
import com.hwilliams.agroServer.db.model.CotizacionExample.Criterion;
import com.hwilliams.agroServer.db.model.CotizacionExample;
import java.util.List;
import java.util.Map;

public class CotizacionSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String countByExample(CotizacionExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("cotizacion");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String deleteByExample(CotizacionExample example) {
        BEGIN();
        DELETE_FROM("cotizacion");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String insertSelective(Cotizacion record) {
        BEGIN();
        INSERT_INTO("cotizacion");
        
        if (record.getNombre() != null) {
            VALUES("nombre", "#{nombre,jdbcType=VARCHAR}");
        }
        
        if (record.getMercado() != null) {
            VALUES("mercado", "#{mercado,jdbcType=VARCHAR}");
        }
        
        if (record.getValor() != null) {
            VALUES("valor", "#{valor,jdbcType=VARCHAR}");
        }
        
        if (record.getVariacion() != null) {
            VALUES("variacion", "#{variacion,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String selectByExample(CotizacionExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("nombre");
        } else {
            SELECT("nombre");
        }
        SELECT("mercado");
        SELECT("valor");
        SELECT("variacion");
        FROM("cotizacion");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Cotizacion record = (Cotizacion) parameter.get("record");
        CotizacionExample example = (CotizacionExample) parameter.get("example");
        
        BEGIN();
        UPDATE("cotizacion");
        
        if (record.getNombre() != null) {
            SET("nombre = #{record.nombre,jdbcType=VARCHAR}");
        }
        
        if (record.getMercado() != null) {
            SET("mercado = #{record.mercado,jdbcType=VARCHAR}");
        }
        
        if (record.getValor() != null) {
            SET("valor = #{record.valor,jdbcType=VARCHAR}");
        }
        
        if (record.getVariacion() != null) {
            SET("variacion = #{record.variacion,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("cotizacion");
        
        SET("nombre = #{record.nombre,jdbcType=VARCHAR}");
        SET("mercado = #{record.mercado,jdbcType=VARCHAR}");
        SET("valor = #{record.valor,jdbcType=VARCHAR}");
        SET("variacion = #{record.variacion,jdbcType=VARCHAR}");
        
        CotizacionExample example = (CotizacionExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String updateByPrimaryKeySelective(Cotizacion record) {
        BEGIN();
        UPDATE("cotizacion");
        
        if (record.getMercado() != null) {
            SET("mercado = #{mercado,jdbcType=VARCHAR}");
        }
        
        if (record.getValor() != null) {
            SET("valor = #{valor,jdbcType=VARCHAR}");
        }
        
        if (record.getVariacion() != null) {
            SET("variacion = #{variacion,jdbcType=VARCHAR}");
        }
        
        WHERE("nombre = #{nombre,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    protected void applyWhere(CotizacionExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}