package com.hwilliams.agroServer.db.client;

import com.hwilliams.agroServer.db.model.Maquina;
import com.hwilliams.agroServer.db.model.MaquinaExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MaquinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    @SelectProvider(type=MaquinaSqlProvider.class, method="countByExample")
    int countByExample(MaquinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    @DeleteProvider(type=MaquinaSqlProvider.class, method="deleteByExample")
    int deleteByExample(MaquinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    @Delete({
        "delete from maquina",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    @Insert({
        "insert into maquina (id, tipo, ",
        "marca, modelo)",
        "values (#{id,jdbcType=INTEGER}, #{tipo,jdbcType=VARCHAR}, ",
        "#{marca,jdbcType=VARCHAR}, #{modelo,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT nextVal('maquina_id_seq')", keyProperty="id", before=true, resultType=int.class)
    int insert(Maquina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    @InsertProvider(type=MaquinaSqlProvider.class, method="insertSelective")
    int insertSelective(Maquina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    @SelectProvider(type=MaquinaSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tipo", property="tipo", jdbcType=JdbcType.VARCHAR),
        @Result(column="marca", property="marca", jdbcType=JdbcType.VARCHAR),
        @Result(column="modelo", property="modelo", jdbcType=JdbcType.VARCHAR)
    })
    List<Maquina> selectByExample(MaquinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    @Select({
        "select",
        "id, tipo, marca, modelo",
        "from maquina",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tipo", property="tipo", jdbcType=JdbcType.VARCHAR),
        @Result(column="marca", property="marca", jdbcType=JdbcType.VARCHAR),
        @Result(column="modelo", property="modelo", jdbcType=JdbcType.VARCHAR)
    })
    Maquina selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    @UpdateProvider(type=MaquinaSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Maquina record, @Param("example") MaquinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    @UpdateProvider(type=MaquinaSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Maquina record, @Param("example") MaquinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    @UpdateProvider(type=MaquinaSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Maquina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    @Update({
        "update maquina",
        "set tipo = #{tipo,jdbcType=VARCHAR},",
          "marca = #{marca,jdbcType=VARCHAR},",
          "modelo = #{modelo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Maquina record);
}