package com.hwilliams.agroServer.db.client;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hwilliams.agroServer.db.model.Oferta;
import com.hwilliams.agroServer.db.model.OfertaExample.Criteria;
import com.hwilliams.agroServer.db.model.OfertaExample.Criterion;
import com.hwilliams.agroServer.db.model.OfertaExample;
import java.util.List;
import java.util.Map;

public class OfertaSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oferta
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String countByExample(OfertaExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("oferta");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oferta
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String deleteByExample(OfertaExample example) {
        BEGIN();
        DELETE_FROM("oferta");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oferta
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String insertSelective(Oferta record) {
        BEGIN();
        INSERT_INTO("oferta");
        
        if (record.getUsuarioId() != null) {
            VALUES("usuario_id", "#{usuarioId,jdbcType=INTEGER}");
        }
        
        if (record.getMaquinaId() != null) {
            VALUES("maquina_id", "#{maquinaId,jdbcType=INTEGER}");
        }
        
        if (record.getLatitud() != null) {
            VALUES("latitud", "#{latitud,jdbcType=REAL}");
        }
        
        if (record.getLongitud() != null) {
            VALUES("longitud", "#{longitud,jdbcType=REAL}");
        }
        
        if (record.getDisponibilidadDesde() != null) {
            VALUES("disponibilidad_desde", "#{disponibilidadDesde,jdbcType=DATE}");
        }
        
        if (record.getDisponibilidadHasta() != null) {
            VALUES("disponibilidad_hasta", "#{disponibilidadHasta,jdbcType=DATE}");
        }
        
        if (record.getEstado() != null) {
            VALUES("estado", "#{estado,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oferta
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String selectByExample(OfertaExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("usuario_id");
        } else {
            SELECT("usuario_id");
        }
        SELECT("maquina_id");
        SELECT("latitud");
        SELECT("longitud");
        SELECT("disponibilidad_desde");
        SELECT("disponibilidad_hasta");
        SELECT("estado");
        FROM("oferta");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oferta
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Oferta record = (Oferta) parameter.get("record");
        OfertaExample example = (OfertaExample) parameter.get("example");
        
        BEGIN();
        UPDATE("oferta");
        
        if (record.getUsuarioId() != null) {
            SET("usuario_id = #{record.usuarioId,jdbcType=INTEGER}");
        }
        
        if (record.getMaquinaId() != null) {
            SET("maquina_id = #{record.maquinaId,jdbcType=INTEGER}");
        }
        
        if (record.getLatitud() != null) {
            SET("latitud = #{record.latitud,jdbcType=REAL}");
        }
        
        if (record.getLongitud() != null) {
            SET("longitud = #{record.longitud,jdbcType=REAL}");
        }
        
        if (record.getDisponibilidadDesde() != null) {
            SET("disponibilidad_desde = #{record.disponibilidadDesde,jdbcType=DATE}");
        }
        
        if (record.getDisponibilidadHasta() != null) {
            SET("disponibilidad_hasta = #{record.disponibilidadHasta,jdbcType=DATE}");
        }
        
        if (record.getEstado() != null) {
            SET("estado = #{record.estado,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oferta
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("oferta");
        
        SET("usuario_id = #{record.usuarioId,jdbcType=INTEGER}");
        SET("maquina_id = #{record.maquinaId,jdbcType=INTEGER}");
        SET("latitud = #{record.latitud,jdbcType=REAL}");
        SET("longitud = #{record.longitud,jdbcType=REAL}");
        SET("disponibilidad_desde = #{record.disponibilidadDesde,jdbcType=DATE}");
        SET("disponibilidad_hasta = #{record.disponibilidadHasta,jdbcType=DATE}");
        SET("estado = #{record.estado,jdbcType=VARCHAR}");
        
        OfertaExample example = (OfertaExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oferta
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    protected void applyWhere(OfertaExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}