package com.hwilliams.agroServer.db.client;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hwilliams.agroServer.db.model.ParqueMaquina;
import com.hwilliams.agroServer.db.model.ParqueMaquinaExample.Criteria;
import com.hwilliams.agroServer.db.model.ParqueMaquinaExample.Criterion;
import com.hwilliams.agroServer.db.model.ParqueMaquinaExample;
import java.util.List;
import java.util.Map;

public class ParqueMaquinaSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public String countByExample(ParqueMaquinaExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("parque_maquina");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public String deleteByExample(ParqueMaquinaExample example) {
        BEGIN();
        DELETE_FROM("parque_maquina");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public String insertSelective(ParqueMaquina record) {
        BEGIN();
        INSERT_INTO("parque_maquina");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getRubro() != null) {
            VALUES("rubro", "#{rubro,jdbcType=VARCHAR}");
        }
        
        if (record.getUsuarioId() != null) {
            VALUES("usuario_id", "#{usuarioId,jdbcType=INTEGER}");
        }
        
        if (record.getMaquinasJson() != null) {
            VALUES("maquinas_json", "#{maquinasJson,jdbcType=VARCHAR}");
        }
        
        if (record.getEstado() != null) {
            VALUES("estado", "#{estado,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public String selectByExample(ParqueMaquinaExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("rubro");
        SELECT("usuario_id");
        SELECT("maquinas_json");
        SELECT("estado");
        FROM("parque_maquina");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ParqueMaquina record = (ParqueMaquina) parameter.get("record");
        ParqueMaquinaExample example = (ParqueMaquinaExample) parameter.get("example");
        
        BEGIN();
        UPDATE("parque_maquina");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getRubro() != null) {
            SET("rubro = #{record.rubro,jdbcType=VARCHAR}");
        }
        
        if (record.getUsuarioId() != null) {
            SET("usuario_id = #{record.usuarioId,jdbcType=INTEGER}");
        }
        
        if (record.getMaquinasJson() != null) {
            SET("maquinas_json = #{record.maquinasJson,jdbcType=VARCHAR}");
        }
        
        if (record.getEstado() != null) {
            SET("estado = #{record.estado,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("parque_maquina");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("rubro = #{record.rubro,jdbcType=VARCHAR}");
        SET("usuario_id = #{record.usuarioId,jdbcType=INTEGER}");
        SET("maquinas_json = #{record.maquinasJson,jdbcType=VARCHAR}");
        SET("estado = #{record.estado,jdbcType=VARCHAR}");
        
        ParqueMaquinaExample example = (ParqueMaquinaExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public String updateByPrimaryKeySelective(ParqueMaquina record) {
        BEGIN();
        UPDATE("parque_maquina");
        
        if (record.getRubro() != null) {
            SET("rubro = #{rubro,jdbcType=VARCHAR}");
        }
        
        if (record.getUsuarioId() != null) {
            SET("usuario_id = #{usuarioId,jdbcType=INTEGER}");
        }
        
        if (record.getMaquinasJson() != null) {
            SET("maquinas_json = #{maquinasJson,jdbcType=VARCHAR}");
        }
        
        if (record.getEstado() != null) {
            SET("estado = #{estado,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    protected void applyWhere(ParqueMaquinaExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}