package com.hwilliams.agroServer.db.client;

import com.hwilliams.agroServer.db.model.Prestacion;
import com.hwilliams.agroServer.db.model.PrestacionExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PrestacionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestacion
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @SelectProvider(type=PrestacionSqlProvider.class, method="countByExample")
    int countByExample(PrestacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestacion
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @DeleteProvider(type=PrestacionSqlProvider.class, method="deleteByExample")
    int deleteByExample(PrestacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestacion
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @Delete({
        "delete from prestacion",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestacion
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @Insert({
        "insert into prestacion (id, propietario_id, ",
        "maquina_id, fecha_desde, ",
        "fecha_hasta, cliente_id, ",
        "estado)",
        "values (#{id,jdbcType=INTEGER}, #{propietarioId,jdbcType=INTEGER}, ",
        "#{maquinaId,jdbcType=INTEGER}, #{fechaDesde,jdbcType=DATE}, ",
        "#{fechaHasta,jdbcType=DATE}, #{clienteId,jdbcType=INTEGER}, ",
        "#{estado,jdbcType=VARCHAR})"
    })
    int insert(Prestacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestacion
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @InsertProvider(type=PrestacionSqlProvider.class, method="insertSelective")
    int insertSelective(Prestacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestacion
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @SelectProvider(type=PrestacionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="propietario_id", property="propietarioId", jdbcType=JdbcType.INTEGER),
        @Result(column="maquina_id", property="maquinaId", jdbcType=JdbcType.INTEGER),
        @Result(column="fecha_desde", property="fechaDesde", jdbcType=JdbcType.DATE),
        @Result(column="fecha_hasta", property="fechaHasta", jdbcType=JdbcType.DATE),
        @Result(column="cliente_id", property="clienteId", jdbcType=JdbcType.INTEGER),
        @Result(column="estado", property="estado", jdbcType=JdbcType.VARCHAR)
    })
    List<Prestacion> selectByExample(PrestacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestacion
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @Select({
        "select",
        "id, propietario_id, maquina_id, fecha_desde, fecha_hasta, cliente_id, estado",
        "from prestacion",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="propietario_id", property="propietarioId", jdbcType=JdbcType.INTEGER),
        @Result(column="maquina_id", property="maquinaId", jdbcType=JdbcType.INTEGER),
        @Result(column="fecha_desde", property="fechaDesde", jdbcType=JdbcType.DATE),
        @Result(column="fecha_hasta", property="fechaHasta", jdbcType=JdbcType.DATE),
        @Result(column="cliente_id", property="clienteId", jdbcType=JdbcType.INTEGER),
        @Result(column="estado", property="estado", jdbcType=JdbcType.VARCHAR)
    })
    Prestacion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestacion
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @UpdateProvider(type=PrestacionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Prestacion record, @Param("example") PrestacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestacion
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @UpdateProvider(type=PrestacionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Prestacion record, @Param("example") PrestacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestacion
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @UpdateProvider(type=PrestacionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Prestacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestacion
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @Update({
        "update prestacion",
        "set propietario_id = #{propietarioId,jdbcType=INTEGER},",
          "maquina_id = #{maquinaId,jdbcType=INTEGER},",
          "fecha_desde = #{fechaDesde,jdbcType=DATE},",
          "fecha_hasta = #{fechaHasta,jdbcType=DATE},",
          "cliente_id = #{clienteId,jdbcType=INTEGER},",
          "estado = #{estado,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Prestacion record);
}