package com.hwilliams.agroServer.db.client;

import com.hwilliams.agroServer.db.model.Usuario;
import com.hwilliams.agroServer.db.model.UsuarioExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UsuarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @SelectProvider(type=UsuarioSqlProvider.class, method="countByExample")
    int countByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @DeleteProvider(type=UsuarioSqlProvider.class, method="deleteByExample")
    int deleteByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @Delete({
        "delete from usuario",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @Insert({
        "insert into usuario (id, nombre, ",
        "apellido, telefono_1, ",
        "telefono_2, email)",
        "values (#{id,jdbcType=INTEGER}, #{nombre,jdbcType=VARCHAR}, ",
        "#{apellido,jdbcType=VARCHAR}, #{telefono1,jdbcType=VARCHAR}, ",
        "#{telefono2,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR})"
    })
    int insert(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @InsertProvider(type=UsuarioSqlProvider.class, method="insertSelective")
    int insertSelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @SelectProvider(type=UsuarioSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="nombre", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="apellido", property="apellido", jdbcType=JdbcType.VARCHAR),
        @Result(column="telefono_1", property="telefono1", jdbcType=JdbcType.VARCHAR),
        @Result(column="telefono_2", property="telefono2", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR)
    })
    List<Usuario> selectByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @Select({
        "select",
        "id, nombre, apellido, telefono_1, telefono_2, email",
        "from usuario",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="nombre", property="nombre", jdbcType=JdbcType.VARCHAR),
        @Result(column="apellido", property="apellido", jdbcType=JdbcType.VARCHAR),
        @Result(column="telefono_1", property="telefono1", jdbcType=JdbcType.VARCHAR),
        @Result(column="telefono_2", property="telefono2", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR)
    })
    Usuario selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @UpdateProvider(type=UsuarioSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @UpdateProvider(type=UsuarioSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @UpdateProvider(type=UsuarioSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    @Update({
        "update usuario",
        "set nombre = #{nombre,jdbcType=VARCHAR},",
          "apellido = #{apellido,jdbcType=VARCHAR},",
          "telefono_1 = #{telefono1,jdbcType=VARCHAR},",
          "telefono_2 = #{telefono2,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Usuario record);
}