package com.hwilliams.agroServer.db.model;

public class Clima {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clima.latitud
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    private Float latitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clima.longitud
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    private Float longitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clima.temperatura
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    private Short temperatura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clima.sensacion_termica
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    private Short sensacionTermica;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clima.descripcion
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    private String descripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clima.viento
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    private Short viento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clima.humedad
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    private Short humedad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clima.probabilidad_lluvia
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    private Short probabilidadLluvia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clima.latitud
     *
     * @return the value of clima.latitud
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public Float getLatitud() {
        return latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clima.latitud
     *
     * @param latitud the value for clima.latitud
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void setLatitud(Float latitud) {
        this.latitud = latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clima.longitud
     *
     * @return the value of clima.longitud
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public Float getLongitud() {
        return longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clima.longitud
     *
     * @param longitud the value for clima.longitud
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void setLongitud(Float longitud) {
        this.longitud = longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clima.temperatura
     *
     * @return the value of clima.temperatura
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public Short getTemperatura() {
        return temperatura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clima.temperatura
     *
     * @param temperatura the value for clima.temperatura
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void setTemperatura(Short temperatura) {
        this.temperatura = temperatura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clima.sensacion_termica
     *
     * @return the value of clima.sensacion_termica
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public Short getSensacionTermica() {
        return sensacionTermica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clima.sensacion_termica
     *
     * @param sensacionTermica the value for clima.sensacion_termica
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void setSensacionTermica(Short sensacionTermica) {
        this.sensacionTermica = sensacionTermica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clima.descripcion
     *
     * @return the value of clima.descripcion
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clima.descripcion
     *
     * @param descripcion the value for clima.descripcion
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clima.viento
     *
     * @return the value of clima.viento
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public Short getViento() {
        return viento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clima.viento
     *
     * @param viento the value for clima.viento
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void setViento(Short viento) {
        this.viento = viento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clima.humedad
     *
     * @return the value of clima.humedad
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public Short getHumedad() {
        return humedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clima.humedad
     *
     * @param humedad the value for clima.humedad
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void setHumedad(Short humedad) {
        this.humedad = humedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clima.probabilidad_lluvia
     *
     * @return the value of clima.probabilidad_lluvia
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public Short getProbabilidadLluvia() {
        return probabilidadLluvia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clima.probabilidad_lluvia
     *
     * @param probabilidadLluvia the value for clima.probabilidad_lluvia
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void setProbabilidadLluvia(Short probabilidadLluvia) {
        this.probabilidadLluvia = probabilidadLluvia;
    }
}