package com.hwilliams.agroServer.db.model;

import java.util.ArrayList;
import java.util.List;

public class ClimaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public ClimaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLatitudIsNull() {
            addCriterion("latitud is null");
            return (Criteria) this;
        }

        public Criteria andLatitudIsNotNull() {
            addCriterion("latitud is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudEqualTo(Float value) {
            addCriterion("latitud =", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotEqualTo(Float value) {
            addCriterion("latitud <>", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudGreaterThan(Float value) {
            addCriterion("latitud >", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudGreaterThanOrEqualTo(Float value) {
            addCriterion("latitud >=", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudLessThan(Float value) {
            addCriterion("latitud <", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudLessThanOrEqualTo(Float value) {
            addCriterion("latitud <=", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudIn(List<Float> values) {
            addCriterion("latitud in", values, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotIn(List<Float> values) {
            addCriterion("latitud not in", values, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudBetween(Float value1, Float value2) {
            addCriterion("latitud between", value1, value2, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotBetween(Float value1, Float value2) {
            addCriterion("latitud not between", value1, value2, "latitud");
            return (Criteria) this;
        }

        public Criteria andLongitudIsNull() {
            addCriterion("longitud is null");
            return (Criteria) this;
        }

        public Criteria andLongitudIsNotNull() {
            addCriterion("longitud is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudEqualTo(Float value) {
            addCriterion("longitud =", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotEqualTo(Float value) {
            addCriterion("longitud <>", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudGreaterThan(Float value) {
            addCriterion("longitud >", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudGreaterThanOrEqualTo(Float value) {
            addCriterion("longitud >=", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudLessThan(Float value) {
            addCriterion("longitud <", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudLessThanOrEqualTo(Float value) {
            addCriterion("longitud <=", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudIn(List<Float> values) {
            addCriterion("longitud in", values, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotIn(List<Float> values) {
            addCriterion("longitud not in", values, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudBetween(Float value1, Float value2) {
            addCriterion("longitud between", value1, value2, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotBetween(Float value1, Float value2) {
            addCriterion("longitud not between", value1, value2, "longitud");
            return (Criteria) this;
        }

        public Criteria andTemperaturaIsNull() {
            addCriterion("temperatura is null");
            return (Criteria) this;
        }

        public Criteria andTemperaturaIsNotNull() {
            addCriterion("temperatura is not null");
            return (Criteria) this;
        }

        public Criteria andTemperaturaEqualTo(Short value) {
            addCriterion("temperatura =", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaNotEqualTo(Short value) {
            addCriterion("temperatura <>", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaGreaterThan(Short value) {
            addCriterion("temperatura >", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaGreaterThanOrEqualTo(Short value) {
            addCriterion("temperatura >=", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaLessThan(Short value) {
            addCriterion("temperatura <", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaLessThanOrEqualTo(Short value) {
            addCriterion("temperatura <=", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaIn(List<Short> values) {
            addCriterion("temperatura in", values, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaNotIn(List<Short> values) {
            addCriterion("temperatura not in", values, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaBetween(Short value1, Short value2) {
            addCriterion("temperatura between", value1, value2, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaNotBetween(Short value1, Short value2) {
            addCriterion("temperatura not between", value1, value2, "temperatura");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaIsNull() {
            addCriterion("sensacion_termica is null");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaIsNotNull() {
            addCriterion("sensacion_termica is not null");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaEqualTo(Short value) {
            addCriterion("sensacion_termica =", value, "sensacionTermica");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaNotEqualTo(Short value) {
            addCriterion("sensacion_termica <>", value, "sensacionTermica");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaGreaterThan(Short value) {
            addCriterion("sensacion_termica >", value, "sensacionTermica");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaGreaterThanOrEqualTo(Short value) {
            addCriterion("sensacion_termica >=", value, "sensacionTermica");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaLessThan(Short value) {
            addCriterion("sensacion_termica <", value, "sensacionTermica");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaLessThanOrEqualTo(Short value) {
            addCriterion("sensacion_termica <=", value, "sensacionTermica");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaIn(List<Short> values) {
            addCriterion("sensacion_termica in", values, "sensacionTermica");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaNotIn(List<Short> values) {
            addCriterion("sensacion_termica not in", values, "sensacionTermica");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaBetween(Short value1, Short value2) {
            addCriterion("sensacion_termica between", value1, value2, "sensacionTermica");
            return (Criteria) this;
        }

        public Criteria andSensacionTermicaNotBetween(Short value1, Short value2) {
            addCriterion("sensacion_termica not between", value1, value2, "sensacionTermica");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("descripcion is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("descripcion is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("descripcion =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("descripcion <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("descripcion >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("descripcion <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("descripcion <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("descripcion like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("descripcion not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("descripcion in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("descripcion not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("descripcion between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("descripcion not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andVientoIsNull() {
            addCriterion("viento is null");
            return (Criteria) this;
        }

        public Criteria andVientoIsNotNull() {
            addCriterion("viento is not null");
            return (Criteria) this;
        }

        public Criteria andVientoEqualTo(Short value) {
            addCriterion("viento =", value, "viento");
            return (Criteria) this;
        }

        public Criteria andVientoNotEqualTo(Short value) {
            addCriterion("viento <>", value, "viento");
            return (Criteria) this;
        }

        public Criteria andVientoGreaterThan(Short value) {
            addCriterion("viento >", value, "viento");
            return (Criteria) this;
        }

        public Criteria andVientoGreaterThanOrEqualTo(Short value) {
            addCriterion("viento >=", value, "viento");
            return (Criteria) this;
        }

        public Criteria andVientoLessThan(Short value) {
            addCriterion("viento <", value, "viento");
            return (Criteria) this;
        }

        public Criteria andVientoLessThanOrEqualTo(Short value) {
            addCriterion("viento <=", value, "viento");
            return (Criteria) this;
        }

        public Criteria andVientoIn(List<Short> values) {
            addCriterion("viento in", values, "viento");
            return (Criteria) this;
        }

        public Criteria andVientoNotIn(List<Short> values) {
            addCriterion("viento not in", values, "viento");
            return (Criteria) this;
        }

        public Criteria andVientoBetween(Short value1, Short value2) {
            addCriterion("viento between", value1, value2, "viento");
            return (Criteria) this;
        }

        public Criteria andVientoNotBetween(Short value1, Short value2) {
            addCriterion("viento not between", value1, value2, "viento");
            return (Criteria) this;
        }

        public Criteria andHumedadIsNull() {
            addCriterion("humedad is null");
            return (Criteria) this;
        }

        public Criteria andHumedadIsNotNull() {
            addCriterion("humedad is not null");
            return (Criteria) this;
        }

        public Criteria andHumedadEqualTo(Short value) {
            addCriterion("humedad =", value, "humedad");
            return (Criteria) this;
        }

        public Criteria andHumedadNotEqualTo(Short value) {
            addCriterion("humedad <>", value, "humedad");
            return (Criteria) this;
        }

        public Criteria andHumedadGreaterThan(Short value) {
            addCriterion("humedad >", value, "humedad");
            return (Criteria) this;
        }

        public Criteria andHumedadGreaterThanOrEqualTo(Short value) {
            addCriterion("humedad >=", value, "humedad");
            return (Criteria) this;
        }

        public Criteria andHumedadLessThan(Short value) {
            addCriterion("humedad <", value, "humedad");
            return (Criteria) this;
        }

        public Criteria andHumedadLessThanOrEqualTo(Short value) {
            addCriterion("humedad <=", value, "humedad");
            return (Criteria) this;
        }

        public Criteria andHumedadIn(List<Short> values) {
            addCriterion("humedad in", values, "humedad");
            return (Criteria) this;
        }

        public Criteria andHumedadNotIn(List<Short> values) {
            addCriterion("humedad not in", values, "humedad");
            return (Criteria) this;
        }

        public Criteria andHumedadBetween(Short value1, Short value2) {
            addCriterion("humedad between", value1, value2, "humedad");
            return (Criteria) this;
        }

        public Criteria andHumedadNotBetween(Short value1, Short value2) {
            addCriterion("humedad not between", value1, value2, "humedad");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaIsNull() {
            addCriterion("probabilidad_lluvia is null");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaIsNotNull() {
            addCriterion("probabilidad_lluvia is not null");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaEqualTo(Short value) {
            addCriterion("probabilidad_lluvia =", value, "probabilidadLluvia");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaNotEqualTo(Short value) {
            addCriterion("probabilidad_lluvia <>", value, "probabilidadLluvia");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaGreaterThan(Short value) {
            addCriterion("probabilidad_lluvia >", value, "probabilidadLluvia");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaGreaterThanOrEqualTo(Short value) {
            addCriterion("probabilidad_lluvia >=", value, "probabilidadLluvia");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaLessThan(Short value) {
            addCriterion("probabilidad_lluvia <", value, "probabilidadLluvia");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaLessThanOrEqualTo(Short value) {
            addCriterion("probabilidad_lluvia <=", value, "probabilidadLluvia");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaIn(List<Short> values) {
            addCriterion("probabilidad_lluvia in", values, "probabilidadLluvia");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaNotIn(List<Short> values) {
            addCriterion("probabilidad_lluvia not in", values, "probabilidadLluvia");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaBetween(Short value1, Short value2) {
            addCriterion("probabilidad_lluvia between", value1, value2, "probabilidadLluvia");
            return (Criteria) this;
        }

        public Criteria andProbabilidadLluviaNotBetween(Short value1, Short value2) {
            addCriterion("probabilidad_lluvia not between", value1, value2, "probabilidadLluvia");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clima
     *
     * @mbggenerated do_not_delete_during_merge Fri May 27 21:07:43 ART 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clima
     *
     * @mbggenerated Fri May 27 21:07:43 ART 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}