package com.hwilliams.agroServer.db.model;

public class Cotizacion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cotizacion.nombre
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cotizacion.mercado
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    private String mercado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cotizacion.valor
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    private String valor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cotizacion.variacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    private String variacion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cotizacion.nombre
     *
     * @return the value of cotizacion.nombre
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cotizacion.nombre
     *
     * @param nombre the value for cotizacion.nombre
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cotizacion.mercado
     *
     * @return the value of cotizacion.mercado
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String getMercado() {
        return mercado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cotizacion.mercado
     *
     * @param mercado the value for cotizacion.mercado
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public void setMercado(String mercado) {
        this.mercado = mercado == null ? null : mercado.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cotizacion.valor
     *
     * @return the value of cotizacion.valor
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String getValor() {
        return valor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cotizacion.valor
     *
     * @param valor the value for cotizacion.valor
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public void setValor(String valor) {
        this.valor = valor == null ? null : valor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cotizacion.variacion
     *
     * @return the value of cotizacion.variacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String getVariacion() {
        return variacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cotizacion.variacion
     *
     * @param variacion the value for cotizacion.variacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public void setVariacion(String variacion) {
        this.variacion = variacion == null ? null : variacion.trim();
    }
}