package com.hwilliams.agroServer.db.model;

import java.util.ArrayList;
import java.util.List;

public class CotizacionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public CotizacionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNombreIsNull() {
            addCriterion("nombre is null");
            return (Criteria) this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("nombre is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("nombre =", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("nombre <>", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("nombre >", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("nombre >=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("nombre <", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("nombre <=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("nombre like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("nombre not like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("nombre in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("nombre not in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("nombre between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("nombre not between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andMercadoIsNull() {
            addCriterion("mercado is null");
            return (Criteria) this;
        }

        public Criteria andMercadoIsNotNull() {
            addCriterion("mercado is not null");
            return (Criteria) this;
        }

        public Criteria andMercadoEqualTo(String value) {
            addCriterion("mercado =", value, "mercado");
            return (Criteria) this;
        }

        public Criteria andMercadoNotEqualTo(String value) {
            addCriterion("mercado <>", value, "mercado");
            return (Criteria) this;
        }

        public Criteria andMercadoGreaterThan(String value) {
            addCriterion("mercado >", value, "mercado");
            return (Criteria) this;
        }

        public Criteria andMercadoGreaterThanOrEqualTo(String value) {
            addCriterion("mercado >=", value, "mercado");
            return (Criteria) this;
        }

        public Criteria andMercadoLessThan(String value) {
            addCriterion("mercado <", value, "mercado");
            return (Criteria) this;
        }

        public Criteria andMercadoLessThanOrEqualTo(String value) {
            addCriterion("mercado <=", value, "mercado");
            return (Criteria) this;
        }

        public Criteria andMercadoLike(String value) {
            addCriterion("mercado like", value, "mercado");
            return (Criteria) this;
        }

        public Criteria andMercadoNotLike(String value) {
            addCriterion("mercado not like", value, "mercado");
            return (Criteria) this;
        }

        public Criteria andMercadoIn(List<String> values) {
            addCriterion("mercado in", values, "mercado");
            return (Criteria) this;
        }

        public Criteria andMercadoNotIn(List<String> values) {
            addCriterion("mercado not in", values, "mercado");
            return (Criteria) this;
        }

        public Criteria andMercadoBetween(String value1, String value2) {
            addCriterion("mercado between", value1, value2, "mercado");
            return (Criteria) this;
        }

        public Criteria andMercadoNotBetween(String value1, String value2) {
            addCriterion("mercado not between", value1, value2, "mercado");
            return (Criteria) this;
        }

        public Criteria andValorIsNull() {
            addCriterion("valor is null");
            return (Criteria) this;
        }

        public Criteria andValorIsNotNull() {
            addCriterion("valor is not null");
            return (Criteria) this;
        }

        public Criteria andValorEqualTo(String value) {
            addCriterion("valor =", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorNotEqualTo(String value) {
            addCriterion("valor <>", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorGreaterThan(String value) {
            addCriterion("valor >", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorGreaterThanOrEqualTo(String value) {
            addCriterion("valor >=", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorLessThan(String value) {
            addCriterion("valor <", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorLessThanOrEqualTo(String value) {
            addCriterion("valor <=", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorLike(String value) {
            addCriterion("valor like", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorNotLike(String value) {
            addCriterion("valor not like", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorIn(List<String> values) {
            addCriterion("valor in", values, "valor");
            return (Criteria) this;
        }

        public Criteria andValorNotIn(List<String> values) {
            addCriterion("valor not in", values, "valor");
            return (Criteria) this;
        }

        public Criteria andValorBetween(String value1, String value2) {
            addCriterion("valor between", value1, value2, "valor");
            return (Criteria) this;
        }

        public Criteria andValorNotBetween(String value1, String value2) {
            addCriterion("valor not between", value1, value2, "valor");
            return (Criteria) this;
        }

        public Criteria andVariacionIsNull() {
            addCriterion("variacion is null");
            return (Criteria) this;
        }

        public Criteria andVariacionIsNotNull() {
            addCriterion("variacion is not null");
            return (Criteria) this;
        }

        public Criteria andVariacionEqualTo(String value) {
            addCriterion("variacion =", value, "variacion");
            return (Criteria) this;
        }

        public Criteria andVariacionNotEqualTo(String value) {
            addCriterion("variacion <>", value, "variacion");
            return (Criteria) this;
        }

        public Criteria andVariacionGreaterThan(String value) {
            addCriterion("variacion >", value, "variacion");
            return (Criteria) this;
        }

        public Criteria andVariacionGreaterThanOrEqualTo(String value) {
            addCriterion("variacion >=", value, "variacion");
            return (Criteria) this;
        }

        public Criteria andVariacionLessThan(String value) {
            addCriterion("variacion <", value, "variacion");
            return (Criteria) this;
        }

        public Criteria andVariacionLessThanOrEqualTo(String value) {
            addCriterion("variacion <=", value, "variacion");
            return (Criteria) this;
        }

        public Criteria andVariacionLike(String value) {
            addCriterion("variacion like", value, "variacion");
            return (Criteria) this;
        }

        public Criteria andVariacionNotLike(String value) {
            addCriterion("variacion not like", value, "variacion");
            return (Criteria) this;
        }

        public Criteria andVariacionIn(List<String> values) {
            addCriterion("variacion in", values, "variacion");
            return (Criteria) this;
        }

        public Criteria andVariacionNotIn(List<String> values) {
            addCriterion("variacion not in", values, "variacion");
            return (Criteria) this;
        }

        public Criteria andVariacionBetween(String value1, String value2) {
            addCriterion("variacion between", value1, value2, "variacion");
            return (Criteria) this;
        }

        public Criteria andVariacionNotBetween(String value1, String value2) {
            addCriterion("variacion not between", value1, value2, "variacion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cotizacion
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 18 15:30:55 ART 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cotizacion
     *
     * @mbggenerated Sat Jun 18 15:30:55 ART 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}