package com.hwilliams.agroServer.db.model;

public class Maquina {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maquina.id
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maquina.tipo
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    private String tipo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maquina.marca
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    private String marca;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maquina.modelo
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    private String modelo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maquina.atributos
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    private Object atributos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maquina.imagen
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    private byte[] imagen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maquina.id
     *
     * @return the value of maquina.id
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maquina.id
     *
     * @param id the value for maquina.id
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maquina.tipo
     *
     * @return the value of maquina.tipo
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maquina.tipo
     *
     * @param tipo the value for maquina.tipo
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public void setTipo(String tipo) {
        this.tipo = tipo == null ? null : tipo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maquina.marca
     *
     * @return the value of maquina.marca
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public String getMarca() {
        return marca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maquina.marca
     *
     * @param marca the value for maquina.marca
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public void setMarca(String marca) {
        this.marca = marca == null ? null : marca.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maquina.modelo
     *
     * @return the value of maquina.modelo
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public String getModelo() {
        return modelo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maquina.modelo
     *
     * @param modelo the value for maquina.modelo
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public void setModelo(String modelo) {
        this.modelo = modelo == null ? null : modelo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maquina.atributos
     *
     * @return the value of maquina.atributos
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public Object getAtributos() {
        return atributos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maquina.atributos
     *
     * @param atributos the value for maquina.atributos
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public void setAtributos(Object atributos) {
        this.atributos = atributos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maquina.imagen
     *
     * @return the value of maquina.imagen
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public byte[] getImagen() {
        return imagen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maquina.imagen
     *
     * @param imagen the value for maquina.imagen
     *
     * @mbggenerated Tue Jul 19 14:30:03 ART 2016
     */
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
}