package com.hwilliams.agroServer.db.model;

import java.util.ArrayList;
import java.util.List;

public class MaquinaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    public MaquinaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTipoIsNull() {
            addCriterion("tipo is null");
            return (Criteria) this;
        }

        public Criteria andTipoIsNotNull() {
            addCriterion("tipo is not null");
            return (Criteria) this;
        }

        public Criteria andTipoEqualTo(String value) {
            addCriterion("tipo =", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotEqualTo(String value) {
            addCriterion("tipo <>", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoGreaterThan(String value) {
            addCriterion("tipo >", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoGreaterThanOrEqualTo(String value) {
            addCriterion("tipo >=", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLessThan(String value) {
            addCriterion("tipo <", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLessThanOrEqualTo(String value) {
            addCriterion("tipo <=", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLike(String value) {
            addCriterion("tipo like", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotLike(String value) {
            addCriterion("tipo not like", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoIn(List<String> values) {
            addCriterion("tipo in", values, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotIn(List<String> values) {
            addCriterion("tipo not in", values, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoBetween(String value1, String value2) {
            addCriterion("tipo between", value1, value2, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotBetween(String value1, String value2) {
            addCriterion("tipo not between", value1, value2, "tipo");
            return (Criteria) this;
        }

        public Criteria andMarcaIsNull() {
            addCriterion("marca is null");
            return (Criteria) this;
        }

        public Criteria andMarcaIsNotNull() {
            addCriterion("marca is not null");
            return (Criteria) this;
        }

        public Criteria andMarcaEqualTo(String value) {
            addCriterion("marca =", value, "marca");
            return (Criteria) this;
        }

        public Criteria andMarcaNotEqualTo(String value) {
            addCriterion("marca <>", value, "marca");
            return (Criteria) this;
        }

        public Criteria andMarcaGreaterThan(String value) {
            addCriterion("marca >", value, "marca");
            return (Criteria) this;
        }

        public Criteria andMarcaGreaterThanOrEqualTo(String value) {
            addCriterion("marca >=", value, "marca");
            return (Criteria) this;
        }

        public Criteria andMarcaLessThan(String value) {
            addCriterion("marca <", value, "marca");
            return (Criteria) this;
        }

        public Criteria andMarcaLessThanOrEqualTo(String value) {
            addCriterion("marca <=", value, "marca");
            return (Criteria) this;
        }

        public Criteria andMarcaLike(String value) {
            addCriterion("marca like", value, "marca");
            return (Criteria) this;
        }

        public Criteria andMarcaNotLike(String value) {
            addCriterion("marca not like", value, "marca");
            return (Criteria) this;
        }

        public Criteria andMarcaIn(List<String> values) {
            addCriterion("marca in", values, "marca");
            return (Criteria) this;
        }

        public Criteria andMarcaNotIn(List<String> values) {
            addCriterion("marca not in", values, "marca");
            return (Criteria) this;
        }

        public Criteria andMarcaBetween(String value1, String value2) {
            addCriterion("marca between", value1, value2, "marca");
            return (Criteria) this;
        }

        public Criteria andMarcaNotBetween(String value1, String value2) {
            addCriterion("marca not between", value1, value2, "marca");
            return (Criteria) this;
        }

        public Criteria andModeloIsNull() {
            addCriterion("modelo is null");
            return (Criteria) this;
        }

        public Criteria andModeloIsNotNull() {
            addCriterion("modelo is not null");
            return (Criteria) this;
        }

        public Criteria andModeloEqualTo(String value) {
            addCriterion("modelo =", value, "modelo");
            return (Criteria) this;
        }

        public Criteria andModeloNotEqualTo(String value) {
            addCriterion("modelo <>", value, "modelo");
            return (Criteria) this;
        }

        public Criteria andModeloGreaterThan(String value) {
            addCriterion("modelo >", value, "modelo");
            return (Criteria) this;
        }

        public Criteria andModeloGreaterThanOrEqualTo(String value) {
            addCriterion("modelo >=", value, "modelo");
            return (Criteria) this;
        }

        public Criteria andModeloLessThan(String value) {
            addCriterion("modelo <", value, "modelo");
            return (Criteria) this;
        }

        public Criteria andModeloLessThanOrEqualTo(String value) {
            addCriterion("modelo <=", value, "modelo");
            return (Criteria) this;
        }

        public Criteria andModeloLike(String value) {
            addCriterion("modelo like", value, "modelo");
            return (Criteria) this;
        }

        public Criteria andModeloNotLike(String value) {
            addCriterion("modelo not like", value, "modelo");
            return (Criteria) this;
        }

        public Criteria andModeloIn(List<String> values) {
            addCriterion("modelo in", values, "modelo");
            return (Criteria) this;
        }

        public Criteria andModeloNotIn(List<String> values) {
            addCriterion("modelo not in", values, "modelo");
            return (Criteria) this;
        }

        public Criteria andModeloBetween(String value1, String value2) {
            addCriterion("modelo between", value1, value2, "modelo");
            return (Criteria) this;
        }

        public Criteria andModeloNotBetween(String value1, String value2) {
            addCriterion("modelo not between", value1, value2, "modelo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table maquina
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 05 23:29:52 ART 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table maquina
     *
     * @mbggenerated Tue Jul 05 23:29:52 ART 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}