package com.hwilliams.agroServer.db.model;

public class Maquina {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maquina.id
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maquina.tipo
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    private String tipo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maquina.marca
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    private String marca;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maquina.modelo
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    private String modelo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maquina.id
     *
     * @return the value of maquina.id
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maquina.id
     *
     * @param id the value for maquina.id
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maquina.tipo
     *
     * @return the value of maquina.tipo
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maquina.tipo
     *
     * @param tipo the value for maquina.tipo
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    public void setTipo(String tipo) {
        this.tipo = tipo == null ? null : tipo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maquina.marca
     *
     * @return the value of maquina.marca
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    public String getMarca() {
        return marca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maquina.marca
     *
     * @param marca the value for maquina.marca
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    public void setMarca(String marca) {
        this.marca = marca == null ? null : marca.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maquina.modelo
     *
     * @return the value of maquina.modelo
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    public String getModelo() {
        return modelo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maquina.modelo
     *
     * @param modelo the value for maquina.modelo
     *
     * @mbggenerated Wed Jun 29 19:27:31 ART 2016
     */
    public void setModelo(String modelo) {
        this.modelo = modelo == null ? null : modelo.trim();
    }
}