package com.hwilliams.agroServer.db.model;

import java.util.Date;

public class Oferta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oferta.usuario_id
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private Integer usuarioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oferta.maquina_id
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private Integer maquinaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oferta.latitud
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private Float latitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oferta.longitud
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private Float longitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oferta.disponibilidad_desde
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private Date disponibilidadDesde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oferta.disponibilidad_hasta
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private Date disponibilidadHasta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oferta.estado
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private String estado;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oferta.usuario_id
     *
     * @return the value of oferta.usuario_id
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public Integer getUsuarioId() {
        return usuarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oferta.usuario_id
     *
     * @param usuarioId the value for oferta.usuario_id
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oferta.maquina_id
     *
     * @return the value of oferta.maquina_id
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public Integer getMaquinaId() {
        return maquinaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oferta.maquina_id
     *
     * @param maquinaId the value for oferta.maquina_id
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setMaquinaId(Integer maquinaId) {
        this.maquinaId = maquinaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oferta.latitud
     *
     * @return the value of oferta.latitud
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public Float getLatitud() {
        return latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oferta.latitud
     *
     * @param latitud the value for oferta.latitud
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setLatitud(Float latitud) {
        this.latitud = latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oferta.longitud
     *
     * @return the value of oferta.longitud
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public Float getLongitud() {
        return longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oferta.longitud
     *
     * @param longitud the value for oferta.longitud
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setLongitud(Float longitud) {
        this.longitud = longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oferta.disponibilidad_desde
     *
     * @return the value of oferta.disponibilidad_desde
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public Date getDisponibilidadDesde() {
        return disponibilidadDesde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oferta.disponibilidad_desde
     *
     * @param disponibilidadDesde the value for oferta.disponibilidad_desde
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setDisponibilidadDesde(Date disponibilidadDesde) {
        this.disponibilidadDesde = disponibilidadDesde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oferta.disponibilidad_hasta
     *
     * @return the value of oferta.disponibilidad_hasta
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public Date getDisponibilidadHasta() {
        return disponibilidadHasta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oferta.disponibilidad_hasta
     *
     * @param disponibilidadHasta the value for oferta.disponibilidad_hasta
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setDisponibilidadHasta(Date disponibilidadHasta) {
        this.disponibilidadHasta = disponibilidadHasta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oferta.estado
     *
     * @return the value of oferta.estado
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oferta.estado
     *
     * @param estado the value for oferta.estado
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }
}