package com.hwilliams.agroServer.db.model;

import java.util.List;

public class ParqueMaquina {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parque_maquina.id
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parque_maquina.rubro
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    private String rubro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parque_maquina.usuario_id
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    private Integer usuarioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parque_maquina.maquinas_json
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    private String maquinasJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parque_maquina.estado
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    private String estado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parque_maquina.lat
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    private Float lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parque_maquina.lon
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    private Float lon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parque_maquina.id
     *
     * @return the value of parque_maquina.id
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parque_maquina.id
     *
     * @param id the value for parque_maquina.id
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parque_maquina.rubro
     *
     * @return the value of parque_maquina.rubro
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public String getRubro() {
        return rubro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parque_maquina.rubro
     *
     * @param rubro the value for parque_maquina.rubro
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public void setRubro(String rubro) {
        this.rubro = rubro == null ? null : rubro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parque_maquina.usuario_id
     *
     * @return the value of parque_maquina.usuario_id
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public Integer getUsuarioId() {
        return usuarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parque_maquina.usuario_id
     *
     * @param usuarioId the value for parque_maquina.usuario_id
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parque_maquina.maquinas_json
     *
     * @return the value of parque_maquina.maquinas_json
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public String getMaquinasJson() {
        return maquinasJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parque_maquina.maquinas_json
     *
     * @param maquinasJson the value for parque_maquina.maquinas_json
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public void setMaquinasJson(String maquinasJson) {
        this.maquinasJson = maquinasJson == null ? null : maquinasJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parque_maquina.estado
     *
     * @return the value of parque_maquina.estado
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parque_maquina.estado
     *
     * @param estado the value for parque_maquina.estado
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parque_maquina.lat
     *
     * @return the value of parque_maquina.lat
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parque_maquina.lat
     *
     * @param lat the value for parque_maquina.lat
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parque_maquina.lon
     *
     * @return the value of parque_maquina.lon
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public Float getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parque_maquina.lon
     *
     * @param lon the value for parque_maquina.lon
     *
     * @mbggenerated Fri Aug 05 00:39:48 ART 2016
     */
    public void setLon(Float lon) {
        this.lon = lon;
    }
    
    private List<Maquina> maquinas;

	public List<Maquina> getMaquinas() {
		return maquinas;
	}

	public void setMaquinas(List<Maquina> maquinas) {
		this.maquinas = maquinas;
	}
}