package com.hwilliams.agroServer.db.model;

import java.util.ArrayList;
import java.util.List;

public class ParqueMaquinaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public ParqueMaquinaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRubroIsNull() {
            addCriterion("rubro is null");
            return (Criteria) this;
        }

        public Criteria andRubroIsNotNull() {
            addCriterion("rubro is not null");
            return (Criteria) this;
        }

        public Criteria andRubroEqualTo(String value) {
            addCriterion("rubro =", value, "rubro");
            return (Criteria) this;
        }

        public Criteria andRubroNotEqualTo(String value) {
            addCriterion("rubro <>", value, "rubro");
            return (Criteria) this;
        }

        public Criteria andRubroGreaterThan(String value) {
            addCriterion("rubro >", value, "rubro");
            return (Criteria) this;
        }

        public Criteria andRubroGreaterThanOrEqualTo(String value) {
            addCriterion("rubro >=", value, "rubro");
            return (Criteria) this;
        }

        public Criteria andRubroLessThan(String value) {
            addCriterion("rubro <", value, "rubro");
            return (Criteria) this;
        }

        public Criteria andRubroLessThanOrEqualTo(String value) {
            addCriterion("rubro <=", value, "rubro");
            return (Criteria) this;
        }

        public Criteria andRubroLike(String value) {
            addCriterion("rubro like", value, "rubro");
            return (Criteria) this;
        }

        public Criteria andRubroNotLike(String value) {
            addCriterion("rubro not like", value, "rubro");
            return (Criteria) this;
        }

        public Criteria andRubroIn(List<String> values) {
            addCriterion("rubro in", values, "rubro");
            return (Criteria) this;
        }

        public Criteria andRubroNotIn(List<String> values) {
            addCriterion("rubro not in", values, "rubro");
            return (Criteria) this;
        }

        public Criteria andRubroBetween(String value1, String value2) {
            addCriterion("rubro between", value1, value2, "rubro");
            return (Criteria) this;
        }

        public Criteria andRubroNotBetween(String value1, String value2) {
            addCriterion("rubro not between", value1, value2, "rubro");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdIsNull() {
            addCriterion("usuario_id is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdIsNotNull() {
            addCriterion("usuario_id is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdEqualTo(Integer value) {
            addCriterion("usuario_id =", value, "usuarioId");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdNotEqualTo(Integer value) {
            addCriterion("usuario_id <>", value, "usuarioId");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdGreaterThan(Integer value) {
            addCriterion("usuario_id >", value, "usuarioId");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("usuario_id >=", value, "usuarioId");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdLessThan(Integer value) {
            addCriterion("usuario_id <", value, "usuarioId");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdLessThanOrEqualTo(Integer value) {
            addCriterion("usuario_id <=", value, "usuarioId");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdIn(List<Integer> values) {
            addCriterion("usuario_id in", values, "usuarioId");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdNotIn(List<Integer> values) {
            addCriterion("usuario_id not in", values, "usuarioId");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdBetween(Integer value1, Integer value2) {
            addCriterion("usuario_id between", value1, value2, "usuarioId");
            return (Criteria) this;
        }

        public Criteria andUsuarioIdNotBetween(Integer value1, Integer value2) {
            addCriterion("usuario_id not between", value1, value2, "usuarioId");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonIsNull() {
            addCriterion("maquinas_json is null");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonIsNotNull() {
            addCriterion("maquinas_json is not null");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonEqualTo(String value) {
            addCriterion("maquinas_json =", value, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonNotEqualTo(String value) {
            addCriterion("maquinas_json <>", value, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonGreaterThan(String value) {
            addCriterion("maquinas_json >", value, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonGreaterThanOrEqualTo(String value) {
            addCriterion("maquinas_json >=", value, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonLessThan(String value) {
            addCriterion("maquinas_json <", value, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonLessThanOrEqualTo(String value) {
            addCriterion("maquinas_json <=", value, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonLike(String value) {
            addCriterion("maquinas_json like", value, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonNotLike(String value) {
            addCriterion("maquinas_json not like", value, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonIn(List<String> values) {
            addCriterion("maquinas_json in", values, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonNotIn(List<String> values) {
            addCriterion("maquinas_json not in", values, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonBetween(String value1, String value2) {
            addCriterion("maquinas_json between", value1, value2, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andMaquinasJsonNotBetween(String value1, String value2) {
            addCriterion("maquinas_json not between", value1, value2, "maquinasJson");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("estado is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("estado is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(String value) {
            addCriterion("estado =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(String value) {
            addCriterion("estado <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(String value) {
            addCriterion("estado >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(String value) {
            addCriterion("estado >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(String value) {
            addCriterion("estado <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(String value) {
            addCriterion("estado <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLike(String value) {
            addCriterion("estado like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotLike(String value) {
            addCriterion("estado not like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<String> values) {
            addCriterion("estado in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<String> values) {
            addCriterion("estado not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(String value1, String value2) {
            addCriterion("estado between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(String value1, String value2) {
            addCriterion("estado not between", value1, value2, "estado");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parque_maquina
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 29 19:27:30 ART 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parque_maquina
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}