package com.hwilliams.agroServer.db.model;

public class Usuario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.id
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.nombre
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.apellido
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private String apellido;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.telefono_1
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private String telefono1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.telefono_2
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private String telefono2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.email
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.id
     *
     * @return the value of usuario.id
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.id
     *
     * @param id the value for usuario.id
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.nombre
     *
     * @return the value of usuario.nombre
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.nombre
     *
     * @param nombre the value for usuario.nombre
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.apellido
     *
     * @return the value of usuario.apellido
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String getApellido() {
        return apellido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.apellido
     *
     * @param apellido the value for usuario.apellido
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setApellido(String apellido) {
        this.apellido = apellido == null ? null : apellido.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.telefono_1
     *
     * @return the value of usuario.telefono_1
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String getTelefono1() {
        return telefono1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.telefono_1
     *
     * @param telefono1 the value for usuario.telefono_1
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1 == null ? null : telefono1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.telefono_2
     *
     * @return the value of usuario.telefono_2
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String getTelefono2() {
        return telefono2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.telefono_2
     *
     * @param telefono2 the value for usuario.telefono_2
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2 == null ? null : telefono2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.email
     *
     * @return the value of usuario.email
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.email
     *
     * @param email the value for usuario.email
     *
     * @mbggenerated Sun Jun 19 15:33:44 ART 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}