package com.hwilliams.agroServer.db.model;

public class Usuario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.id
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.nombre
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.apellido
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    private String apellido;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.telefono
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    private String telefono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.email
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.password
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.id
     *
     * @return the value of usuario.id
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.id
     *
     * @param id the value for usuario.id
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.nombre
     *
     * @return the value of usuario.nombre
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.nombre
     *
     * @param nombre the value for usuario.nombre
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.apellido
     *
     * @return the value of usuario.apellido
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public String getApellido() {
        return apellido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.apellido
     *
     * @param apellido the value for usuario.apellido
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public void setApellido(String apellido) {
        this.apellido = apellido == null ? null : apellido.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.telefono
     *
     * @return the value of usuario.telefono
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.telefono
     *
     * @param telefono the value for usuario.telefono
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono == null ? null : telefono.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.email
     *
     * @return the value of usuario.email
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.email
     *
     * @param email the value for usuario.email
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.password
     *
     * @return the value of usuario.password
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.password
     *
     * @param password the value for usuario.password
     *
     * @mbggenerated Wed Jun 29 19:27:30 ART 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}